spring:
  datasource:
    url: jdbc:h2:mem:personsdb;MODE=PostgreSQL;DATABASE_TO_UPPER=true
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
server:
  port: 8080
